// src/redux/community/community.types.ts

export const FETCH_COMMUNITY_FEED_REQUEST = 'FETCH_COMMUNITY_FEED_REQUEST';
export const FETCH_COMMUNITY_FEED_SUCCESS = 'FETCH_COMMUNITY_FEED_SUCCESS';
export const FETCH_COMMUNITY_FEED_FAILURE = 'FETCH_COMMUNITY_FEED_FAILURE';

// --- New Action Types for Single Post ---
export const FETCH_SINGLE_POST_REQUEST = 'FETCH_SINGLE_POST_REQUEST';
export const FETCH_SINGLE_POST_SUCCESS = 'FETCH_SINGLE_POST_SUCCESS';
export const FETCH_SINGLE_POST_FAILURE = 'FETCH_SINGLE_POST_FAILURE';
// --- End New Action Types ---

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';

export const CLEAR_COMMUNITY_ERROR = 'CLEAR_COMMUNITY_ERROR';