// src/redux/savings/savings.types.js
export const GET_SAVINGS_GOALS_REQUEST = 'GET_SAVINGS_GOALS_REQUEST';
export const GET_SAVINGS_GOALS_SUCCESS = 'GET_SAVINGS_GOALS_SUCCESS';
export const GET_SAVINGS_GOALS_FAILURE = 'GET_SAVINGS_GOALS_FAILURE';

export const GET_DASHBOARD_ANALYTICS_REQUEST = 'GET_DASHBOARD_ANALYTICS_REQUEST';
export const GET_DASHBOARD_ANALYTICS_SUCCESS = 'GET_DASHBOARD_ANALYTICS_SUCCESS';
export const GET_DASHBOARD_ANALYTICS_FAILURE = 'GET_DASHBOARD_ANALYTICS_FAILURE';

// New types for SavingsView
export const GET_SAVINGS_SUMMARY_REQUEST = 'GET_SAVINGS_SUMMARY_REQUEST';
export const GET_SAVINGS_SUMMARY_SUCCESS = 'GET_SAVINGS_SUMMARY_SUCCESS';
export const GET_SAVINGS_SUMMARY_FAILURE = 'GET_SAVINGS_SUMMARY_FAILURE';

export const GET_RECENT_TRANSACTIONS_REQUEST = 'GET_RECENT_TRANSACTIONS_REQUEST';
export const GET_RECENT_TRANSACTIONS_SUCCESS = 'GET_RECENT_TRANSACTIONS_SUCCESS';
export const GET_RECENT_TRANSACTIONS_FAILURE = 'GET_RECENT_TRANSACTIONS_FAILURE';

export const CREATE_SAVINGS_GOAL_REQUEST = 'CREATE_SAVINGS_GOAL_REQUEST';
export const CREATE_SAVINGS_GOAL_SUCCESS = 'CREATE_SAVINGS_GOAL_SUCCESS';
export const CREATE_SAVINGS_GOAL_FAILURE = 'CREATE_SAVINGS_GOAL_FAILURE';

export const INITIATE_DEPOSIT_REQUEST = 'INITIATE_DEPOSIT_REQUEST';
export const INITIATE_DEPOSIT_SUCCESS = 'INITIATE_DEPOSIT_SUCCESS';
export const INITIATE_DEPOSIT_FAILURE = 'INITIATE_DEPOSIT_FAILURE';

export const INITIATE_WITHDRAWAL_REQUEST = 'INITIATE_WITHDRAWAL_REQUEST';
export const INITIATE_WITHDRAWAL_SUCCESS = 'INITIATE_WITHDRAWAL_SUCCESS';
export const INITIATE_WITHDRAWAL_FAILURE = 'INITIATE_WITHDRAWAL_FAILURE';

export const CLEAR_SAVINGS_ERROR = 'CLEAR_SAVINGS_ERROR';


export const GET_WALLET_REQUEST = 'GET_WALLET_REQUEST';
export const GET_WALLET_SUCCESS = 'GET_WALLET_SUCCESS';
export const GET_WALLET_FAILURE = 'GET_WALLET_FAILURE';


export const INITIATE_WALLET_WITHDRAWAL_REQUEST = 'INITIATE_WALLET_WITHDRAWAL_REQUEST';
export const INITIATE_WALLET_WITHDRAWAL_SUCCESS = 'INIIATE_WALLET_WITHDRAWAL_SUCCESS';
export const INITIATE_WALLET_WITHDRAWAL_FAILURE = 'INITIATE_WALLET_WITHDRAWAL_FAILURE';

export const DELETE_SAVINGS_GOAL_REQUEST = 'DELETE_SAVINGS_GOAL_REQUEST';
export const DELETE_SAVINGS_GOAL_SUCCESS = 'DELETE_SAVINGS_GOAL_SUCCESS';
export const DELETE_SAVINGS_GOAL_FAILURE = 'DELETE_SAVINGS_GOAL_FAILURE';


export const GET_SAVINGS_RECENT_TRANSACTIONS_REQUEST = 'GET_SAVINGS_RECENT_TRANSACTIONS_REQUEST';
export const GET_SAVINGS_RECENT_TRANSACTIONS_SUCCESS = 'GET_SAVINGS_RECENT_TRANSACTIONS_SUCCESS';
export const GET_SAVINGS_RECENT_TRANSACTIONS_FAILURE = 'GET_SAVINGS_RECENT_TRANSACTIONS_FAILURE';

export const GET_BANKS_REQUEST = 'GET_BANKS_REQUEST';
export const GET_BANKS_SUCCESS = 'GET_BANKS_SUCCESS';
export const GET_BANKS_FAILURE = 'GET_BANKS_FAILURE';
