export const FETCH_USER_PROFILE_REQUEST = 'FETCH_USER_PROFILE_REQUEST';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE';

export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAILURE = 'UPDATE_USER_PROFILE_FAILURE';


export const UPDATE_BVN_REQUEST = 'UPDATE_BVN_REQUEST';
export const UPDATE_BVN_SUCCESS = 'UPDATE_BVN_SUCCESS';
export const UPDATE_BVN_FAILURE = 'UPDATE_BVN_FAILURE';

export const UPDATE_NIN_REQUEST = 'UPDATE_NIN_REQUEST';
export const UPDATE_NIN_SUCCESS = 'UPDATE_NIN_SUCCESS';
export const UPDATE_NIN_FAILURE = 'UPDATE_NIN_FAILURE';

export const CLEAR_USER_PROFILE_ERROR = 'CLEAR_USER_PROFILE_ERROR';